config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'users/show'
  get 'pages/about'
  get 'pages/manifesto'
  get 'pages/mentions_legales'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :crushes
  resources :crush_libraries
  resources :libraries

  resources :pages, only: [:index]

  root :to => "pages#welcome_page"

  resources :users, only: [:show]

  resources :crushs do
    resources :comments
  end

  resources :conversations, only: [:index, :create, :destroy] do
    resources :messages, only: [:index, :create]
  end

  scope 'admin', module: 'admin', as: 'admin' do
    resources :crushes
  end

end

app/models/crush.rb
class Crush < ApplicationRecord
    include PgSearch::Model

    belongs_to :user
    has_many :crush_libraries, dependent: :destroy
    has_many :libraries, through: :crush_libraries
    has_many :comments, dependent: :destroy

    validates :book_title, :genre, :author_name, :author_country, :description, :quote, presence: { message: 'ne peut pas être laissé vide' }


    pg_search_scope :roughly_spelled_like,
                 against: [:author_name, :book_title],
                 using: {
                   trigram: {
                     threshold: 0.2
                   }
                 }

end

app/controllers/crushes_controller.rb
class CrushesController < ApplicationController

  before_action :authenticate_user!, only:[:new, :create, :edit, :update, :destroy]
  before_action :set_crush, only:[:show, :edit, :update, :destroy]

  def index
    @crushes = Crush.order('created_at DESC').paginate(:page => params[:page], :per_page => 10)

    if params[:term]
      @crushes = Crush.roughly_spelled_like(params[:term]).paginate(:page => params[:page], :per_page => 10)
    end

  end


  def show
  end

  def new
    @crush = Crush.new
  end

  def create
    if !user_signed_in?
      redirect_to new_user_registration_path
    else
    @user = current_user
    @crush = Crush.new(:user => @user, :book_title=> params[:book_title], :genre => params[:genre], :author_name => params[:author_name], :author_country => params[:author_country], :description => params[:description], :quote => params[:quote])
      if @crush.save
        flash[:success] = "Ton coup de cœur est maintenant visible par tout.e.s ! :)"
        redirect_to crushes_path
      else
        flash[:errors] = @crush.errors.full_messages
        render new_crush_path
      end
    end
  end

  def edit
  end

  def update

    if @crush.update(crush_params)
    redirect_to @crush
    else
    render 'edit'
    end
  end

  def destroy
    @crush.destroy
    redirect_to crushes_path
  end

end

private

  def crush_params
    params.require(:crush).permit(:user, :book_title, :genre, :author_name, :author_country, :description, :quote)
  end

  def set_crush
    @crush = Crush.find(params[:id])
  end

app/helpers/crushes_helper.rb
module CrushesHelper
end

app/views/crushes/edit.html.erb
<div class="pricing-header pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4 text-center" id="rubric_chapter">Edite ton coup de coeur</h1>
  <p class="lead" id="rubric_chapter">Elle a compté pour toi ? Elle comptera sûrement pour nous.</p>
</div>


<div class="container">
  <%= form_for @crush, method: :patch do |f| %>
  <div class="form-group text-left">
  <%= f.label 'Titre du livre' %><br>
  <%= f.text_field :book_title , class:'form-control', required:'true', placeholder:"Book Title", autofocus: 'true', id: "inputEmail"%>

  </div>
  <div class="form-group">
    <%= f.label 'Auteure' %><br>
    <%= f.text_field :author_name, class:'form-control', required:'true', placeholder:"Author", autofocus: 'true', id: "inputEmail"%>
  </div>
  <div class="form-group">
    <%= f.label 'Genre' %><br>
    <%= f.text_field :genre, class:'form-control', required:'true', placeholder:"Genre", autofocus: 'true', id: "inputEmail" %>
  </div>
  <div class="form-group">
    <%= f.label 'Pays' %><br>
    <%= f.text_field :author_country, class:'form-control', required:'true', placeholder:"Country", autofocus: 'true', id: "inputEmail" %>
  </div>
  <div class="form-group">
    <%= f.label 'Pourquoi elle est si importante pour toi ?' %><br>
    <%= f.text_area :description, class:'form-control', required:'true', placeholder:"Why did this matter to you ?", autofocus: 'true', id: "inputEmail"%>
  </div>
  <div class="form-group">
    <%= f.label "Une citation qui t'a marqué-e" %><br>
    <%= f.text_field :quote , class:'form-control', required:'true', placeholder:"Why did this matter to you ?", autofocus: 'true', id: "inputEmail"%>
  </div>
  <%= submit_tag "Edite ton crush", class: "btn btn-dark mt-4 justify-align-end", id:"btn-white" %>
  </div>
<% end %>

app/views/crushes/index.html.erb
<html>
  <body>
            <div class="text-center">
              <div class='container pt-5'>
              <h1 class='display-3 text-center presentation_text m-4 p-4' id='keywords'> Partage • Rencontre • Découvre</h1>
                <div class='container d-flex justify-content-center my-4 mb-5'>
                  <div class='container'>
                    <div class='container d-flex justify-content-center my-4 mb-5'>
                      <%if current_user == nil %>
                      <p> <%= link_to "REJOINS-NOUS", new_user_registration_path, class: "btn btn-dark mb-5 ", id: "btn-white"%> </p>
                      <% else %>
                      <p> <%= link_to "AJOUTE TON COUP DE CŒUR", new_crush_path, class:'btn btn-danger rounded-circle d-flex flex-wrap align-content-center', id: 'add_crush_btn'%> </p>
                      <% end %>
                    </div>

                    <% if @crushes.count == 0 %>
                      <p>Aucun partage ne correspond à ta recherche</p>
                    <% end %>

                <div class="row mb-5 d-flex justify-content-center" id="my_anchor">
                  <% @crushes.each do |n| %>
                    <div class="col-lg-9 ">
                      <div class="row">
                        <div class="col-12">
                          <div class="card text-left", id="square">
                            <div class="card-body">
                            <div class="card-title"><%= n.book_title %></div>
                              <p class="card-text pr-4"></p>
                              <div class="card-subtitle mb-3 text-muted"><%= n.created_at.to_formatted_s(:short)%></div>
                                <p class="card-quote">“<%= n.quote.truncate(100) %>”</p>
                                <p class="card-credit"><%= n.author_name%> (<%= n.author_country%>)</p>
                                <div class="d-flex w-100 justify-content-between">
                                  <div>
                                    <ul class="nav nav-pills nav-fill mt-3 mb-2 ">
                                        <li class="nav-item">
                                            <a class="crush-link-btn" id="crush-link" <%= link_to "Consulter", crush_path(n.id)%> </a>
                                        </li>
                                    </ul>
                                  </div>
                                </div>
                              </div>
                          </div>
                        </div>
                      </div><br>
                    </div>
                  <% end %>
                </div>



                <!-- ————————————— Pagination buttons ————————————— -->
                  <div class="container text-center d-flex justify-content-center button-pages ">
                  <%= will_paginate @crushes, class:"px-4"%>

                </div>
                    <div class="container px-5 ">
                        <div  class="alert alert_message text-center p-5 ">
                          <strong><%= flash[:success] %></strong>
                        </div>
                    </div>

                    <div>


                </ul>
              </div>
            </div>
          </div>
        </div
  </body>
</html>

app/views/crushes/new.html.erb
<div class="container-fluid   mx-auto text-center" >
  <h1 class="display-4 text-center mt-5 p-2" id="rubric_chapter">Partage ton coup de coeur !</h1>

  <div class="lead mb-5" id="rubric_chapter">Elle a compté pour toi ? Elle comptera sûrement pour nous.</div>
</div>

<br>


<div class="container pb-4 mb-5">
  <%= form_tag crushes_path, :method => :post do  %>

  <% if !!flash[:errors] %>
    <div id="error_explanation">
      <% flash[:errors].each do |e| %>
      <p><%= e %></p> 
      <% end %>
    </div>
  <% end %>

<br>

  <div class="form-group">
    <%= text_field_tag('book_title', '', class:'form-control invalid', placeholder:"Titre du livre", autofocus: 'true', id: "inputEmail")%>
  </div>
  <div class="form-group">
    <%= text_field_tag('author_name', '', class:'form-control', placeholder:"Autrice", id: "inputEmail")%>
  </div>
  <div class="form-group">
    <%= text_field_tag('genre', '', class:'form-control', placeholder:"Genre", id: "inputEmail")%>
  </div>
  <div class="form-group">
    <%= text_field_tag('author_country', '', class:'form-control', placeholder:"Pays", id: "inputEmail")%>
  </div>
  <div class="form-group">
    <%= text_area_tag('description', '', class:'form-control', placeholder:"Pourquoi a-t-elle compté pour toi ?", id: "inputEmail")%>
  </div>
  <div class="form-group ">
    <%= text_field_tag('quote', '', class:'form-control', placeholder:"Une citation qui t'a marqué.e", id: "inputEmail")%>
  </div>
  <%= submit_tag "Publier", class: "btn btn-dark mt-4 justify-align-end", id:"btn-white" %>
</div>
<% end %>

app/views/crushes/show.html.erb
<div class="container">

<br>
  <div class="card p-2 my-2" id="square">
    <h5 class="card-header border-0" id="title-crush">
      <a> <b><%= @crush.book_title%> </b></a>
    </h5>
      <div class="card-body">
        <p class="card-author "> <%= @crush.user.pseudo %></p>
        <div class="card-subtitle mt-2 mb-2 text-muted" id="kind_of_book"><%= @crush.genre %></div>
        <p class="card-quote">“<%= @crush.quote %>”</p>
        <p class="card-credit"><%= @crush.author_name %> (<%= @crush.author_country %>)</p>
        <p class="card-text"><%= @crush.description%><p>
                <hr>

      <div class="container">

        <% if isNotCrushAuthor? %>
        <ul class="nav nav-pills nav-fill mt-4">

          <li class="nav-item" >
             <%= link_to "Ajouter à ma bibliothèque", crush_libraries_path(:id => @crush), method: :post, class: 'crush-link-btn', id: 'crush-link' %>
          </li>
          <% end %>

        <% if current_user && isNotCrushAuthor? %>
          <li class="nav-item" >
            <%= link_to "Qui a partagé ça ?", user_path(@crush.user), class: "crush-link-btn", id: "crush-link"%>
          </li>
          <% end %>

          <% if isAdmin? && isNotCrushAuthor? %>
          <li class="nav-item" >
            <a class="crush-link-btn" id="crush-link" <%= link_to "Modérer", crush_path(@crush), method: :delete %> </a>
         </li>
          <% end %>

        </ul>
      </div>

      <div class="container d-flex">

        <% if isCrushAuthor? %>
        <ul class="nav nav-pills nav-fill mt-4">

          <li class="nav-item mx-5" >
            <a class="crush-link-btn" id="crush-link" <%= link_to "Editer", edit_crush_path(@crush)%> </a>
          </li>

          <li class="nav-item" >
            <a class="crush-link-btn" id="crush-link" <%= link_to "Supprimer", crush_path(@crush), method: :delete %> </a>
          </li>
        <% end %>

        </ul>

      </div>

      </div>
    </div>

  <div class="row pt-3">
    <div class="col-sm-10">
      <div class="card" id="square">
        <div class="card-body">
          <h5 class="card-title">Commentaire</h5>
          <%= form_tag crush_comments_path(@crush), method: :post do %>
          <div class="form-group">
            <%= text_area_tag :content, placeholder = "Commente ici...", class: 'form-control no-border' %>
          </div>
            <%= submit_tag "Commenter", class: "btn to_comment", id:"get_library_btn_sm"%>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<br>

<div class="container">
  <div class="container text-left">
    <% @crush.comments.each do |comment| %>
      <div class="container">
        <div class="media" >
          <div class="card pt-4 pr-5 pl-4 text-left" id="square">
            <div class="media-body ">
              <h5 class="mt-0 card-title"><b><%= comment.user.pseudo %></b></h5>
              <p class="mt-0 card-subtitle mb-1 text-muted"><%= comment.created_at.to_formatted_s(:long)%></p>
              <p class="mt-0 card-text pb-2" style="color:#212e9b"><%= comment.body %></p>
              <p><div class="delete_com text-center"> <% if current_user && comment.user_id == current_user.id %>
                <%= link_to 'Delete', crush_comment_path(crush_id: @crush, id: comment), method: :delete,class: "btn to_comment", id:"get_library_btn_sm" %> </div></p>
                <% end %>
              </div>
            </div>
          </div>
        </div><br>
      <% end %>
    </div>
  </div>
</div>
<br>