config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'users/show'
  get 'pages/about'
  get 'pages/manifesto'
  get 'pages/mentions_legales'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :crushes
  resources :crush_libraries
  resources :libraries

  resources :pages, only: [:index]

  root :to => "pages#welcome_page"

  resources :users, only: [:show]

  resources :crushs do
    resources :comments
  end

  resources :conversations, only: [:index, :create, :destroy] do
    resources :messages, only: [:index, :create]
  end

  scope 'admin', module: 'admin', as: 'admin' do
    resources :crushes
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  has_one :library
  has_many :crushes
  has_one_attached :avatar

  has_one :library, dependent: :destroy
  has_many :crushes, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :comments, dependent: :destroy

  after_create :create_library
  after_create :set_pseudo

  after_create :welcome_send, unless: :skip_sending_welcome_email
  attr_accessor :skip_sending_welcome_email

  def create_library
    Library.create(user_id: id)
  end

  def set_pseudo
    self.update(pseudo: self.email.split('@')[0].capitalize)
  end


  def welcome_send
    UserMailer.welcome_send(self).deliver
  end

  def show
    #links the new user to its avatar
    user.avatar.attach(params[:avatar])
    @user = User.find(params[:id])
  end

  def self.from_facebook(auth)
    where(facebook_id: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.pseudo = auth.info.name
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  def facebook
    @user = User.from_facebook(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      redirect_to new_user_registration_url
  end
end



  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end


  protected
  
     def after_sign_up_path_for(resource)
       crushes_path
     end

     def after_update_path_for(resource)
       user_path(resource)
     end


  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

    def after_sign_in_path_for(resource)
      crushes_path
    end


  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])

  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="container">
    <h1 class="display-4 text-center p-4" id="rubric_chapter">Profil</h1>

<div class="d-flex justify-content-end">
<% if current_user.id == @user.id %>
  <%= link_to "Edite ton profil", edit_user_registration_path(@user), class: "btn", id: "btn-white" %>
<% else %>
<%= link_to "Envoyer un message à #{@user.pseudo}", conversations_path(sender_id: current_user.id, receiver_id: @user.id), method: :post, class: "btn", id: "btn-white" %>
<% end %>
</div>
  <div class="card p-4 mt-5 mb-5 border-0" id="square">
  <div class="row">
    <div  class= "col-md-4 d-flex align-items-center justify-content-center "> <%= image_tag user_avatar(current_user), class:"image-cropped rounded", style:"width:200px" %> </div>
      <div class="col-md-7">
        <div class="card-body">
          <p class="card-author "> <strong><%= @user.pseudo %></strong></p>
          <p class="card-credit"><%= @user.city %></p>
          <p class="card-text"><%= @user.description %><p>

          <%= link_to "Bibliothèque", library_path(@user.library), class: "btn", id: "get_library_btn_sm" %>
      </div>
    </div>
  </div>
</div>

    <div class="card p-4 mt-5 mb-5 border-0" id="square" >
      <h2 class="card-title p-4 text-center">Les coups de cœur de <%= @user.pseudo %></h2>

      <% if current_user != @user && @user.crushes.blank? %>
        <p class="card-body text-center"> <%= "#{@user.pseudo} n'a rien partagé pour l'instant" %> <p>

      <% elsif current_user == @user && @user.crushes.blank? %>
      
      <div class= "container text-center">
        <p class="card-body text-center">Tu n'as rien partagé pour l'instant.<p>
        <%= link_to "Partage ton coup de coeur", new_crush_path, class: "btn", id: "get_library_btn_sm" %>
      </div>

      <% else %>
        <div class="row">
          <% @user.crushes.each do |n| %>
            <div class="col-6">
              <div class="row">
                <div class="col-12">
                  <div class="card" id="square" style="border:solid 1px #212e9b">
                    <div class="card-body">
                     <div class="card-title"><%= n.book_title %></div>
                      <p class="card-text"></p>
                      <div class="card-subtitle mb-3 text-muted"><%= n.created_at.to_formatted_s(:long)%></div>
                        <p class="card-quote">“<%= n.quote %>”</p>
                        <p class="card-credit"><%= n.author_name%> (<%= n.author_country%>)</p>
                        <div class="d-flex w-100 justify-content-between">
                          <div>
                            <ul class="nav nav-pills nav-fill mt-3">
                                <li class="nav-item">
                                    <a class="crush-link-btn" id="crush-link" <%= link_to "Consulter", crush_path(n.id)%> </a>
                                </li>
                            </ul>
                          </div>
                        </div>
                      </div>
                  </div>
                </div>
              </div><br>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>