config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'users/show'
  get 'pages/about'
  get 'pages/manifesto'
  get 'pages/mentions_legales'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :crushes
  resources :crush_libraries
  resources :libraries

  resources :pages, only: [:index]

  root :to => "pages#welcome_page"

  resources :users, only: [:show]

  resources :crushs do
    resources :comments
  end

  resources :conversations, only: [:index, :create, :destroy] do
    resources :messages, only: [:index, :create]
  end

  scope 'admin', module: 'admin', as: 'admin' do
    resources :crushes
  end

end

app/models/library.rb
class Library < ApplicationRecord
  belongs_to :user
  has_many :crush_libraries, dependent: :destroy
  has_many :crushes, through: :crush_libraries

  def add_crush(crush)
     current_crush = crush_libraries.find_by(crush_id: crush.id)
     if !current_crush
       current_crush = crush_libraries.create(crush_id: crush.id)
     end
     current_crush
  end

end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
before_action :authenticate_user!

  def index
    @libraries = Library.all
  end

  def show
    @user = User.find(params[:id])
    @library = Library.find_by(user_id: @user.id)
  end

end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
    <h1 class="display-4 text-center p-4" id="rubric_chapter">Bibliothèque</h1>
    <div class="row">

    <% if current_user != @user && @user.library.crushes.blank? %>
      <p class="card-body text-center"> <%= "#{@user.pseudo} n'a rien rangé dans sa bibliothèque pour l'instant" %> <p>

    <% elsif current_user == @user && @user.library.crushes.blank? %>
      <div class= "container text-center">
        <p class="card-body text-center">Tu n'as rien rangé dans ta bibliothèque pour l'instant.<p>
      </div>

    <% else %>
      <% @user.library.crushes.each do |crush| %>
              <div class="col-sm-6 mb-4 ">

              <div class="row">
              <div class="col-12">
                <div class="card border-0" id="square">
                  <div class="card-body">
                   <div class="card-title"> <%= crush.book_title %></div>
                    <p class="card-text"></p>
                    <div class="card-subtitle mb-3 text-muted"></div>
                      <p class="card-quote">“<%= crush.quote %>”</p>
                      <p class="card-credit"><%= crush.author_name %> (<%= crush.author_country%>)</p>
                      <div class="row d-flex justify-content-around ml-0">
                        <div class="text-center">
                          <%= link_to "Consulter", crush_path(crush), class:"btn ", id: "btn-remove" %>
                        </div>
                        <div class="text-center">
                          <% if current_user == @user %>
                        <%= link_to "Supprimer", crush_library_path, :method=>:delete, class:"btn", id: "btn-remove" %>
                          <% end %>
                        </div>
                      </div>
                    </div>
                </div>
              </div>
              </div>
            </div><br>


            <% end %>
        <% end %>
          <br>

</div>


          <!-- ——————————————————————— BUTTON ——————————————————————— -->

          <div class="d-flex bd-highlight">
            <div class="p-2 bd-highlight align-items-end" id="btn-right">
            <%= link_to 'Retour', crushes_path , :class => "btn  btn-dark ",  id: "btn-signin-signup" %>
            </div>
          </div>
</div>