config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'users/show'
  get 'pages/about'
  get 'pages/manifesto'
  get 'pages/mentions_legales'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :crushes
  resources :crush_libraries
  resources :libraries

  resources :pages, only: [:index]

  root :to => "pages#welcome_page"

  resources :users, only: [:show]

  resources :crushs do
    resources :comments
  end

  resources :conversations, only: [:index, :create, :destroy] do
    resources :messages, only: [:index, :create]
  end

  scope 'admin', module: 'admin', as: 'admin' do
    resources :crushes
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :crush
end

app/models/conversation.rb
class Conversation < ApplicationRecord

  belongs_to :sender, class_name: 'User', foreign_key: 'sender_id', optional: true
  belongs_to :receiver, class_name: 'User', foreign_key: 'receiver_id', optional: true
  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :receiver_id

  scope :between, -> (sender_id,receiver_id) do
   where("(conversations.sender_id = ? AND conversations.receiver_id = ?) OR (conversations.receiver_id = ? AND conversations.sender_id = ?)", sender_id, receiver_id, sender_id, receiver_id)
 end
end

app/models/crush.rb
class Crush < ApplicationRecord
    include PgSearch::Model

    belongs_to :user
    has_many :crush_libraries, dependent: :destroy
    has_many :libraries, through: :crush_libraries
    has_many :comments, dependent: :destroy

    validates :book_title, :genre, :author_name, :author_country, :description, :quote, presence: { message: 'ne peut pas être laissé vide' }


    pg_search_scope :roughly_spelled_like,
                 against: [:author_name, :book_title],
                 using: {
                   trigram: {
                     threshold: 0.2
                   }
                 }

end

app/models/crush_library.rb
class CrushLibrary < ApplicationRecord
  belongs_to :crush
  belongs_to :library
end

app/models/library.rb
class Library < ApplicationRecord
  belongs_to :user
  has_many :crush_libraries, dependent: :destroy
  has_many :crushes, through: :crush_libraries

  def add_crush(crush)
     current_crush = crush_libraries.find_by(crush_id: crush.id)
     if !current_crush
       current_crush = crush_libraries.create(crush_id: crush.id)
     end
     current_crush
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

private

    def message_time
      created_at.strftime('%m/%d/%y at %l:%M %p')
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  has_one :library
  has_many :crushes
  has_one_attached :avatar

  has_one :library, dependent: :destroy
  has_many :crushes, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :comments, dependent: :destroy

  after_create :create_library
  after_create :set_pseudo

  after_create :welcome_send, unless: :skip_sending_welcome_email
  attr_accessor :skip_sending_welcome_email

  def create_library
    Library.create(user_id: id)
  end

  def set_pseudo
    self.update(pseudo: self.email.split('@')[0].capitalize)
  end


  def welcome_send
    UserMailer.welcome_send(self).deliver
  end

  def show
    #links the new user to its avatar
    user.avatar.attach(params[:avatar])
    @user = User.find(params[:id])
  end

  def self.from_facebook(auth)
    where(facebook_id: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.pseudo = auth.info.name
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/crushes_controller.rb
class CrushesController < ApplicationController

  before_action :authenticate_user!, only:[:new, :create, :edit, :update, :destroy]
  before_action :set_crush, only:[:show, :edit, :update, :destroy]

  def index
    @crushes = Crush.order('created_at DESC').paginate(:page => params[:page], :per_page => 10)

    if params[:term]
      @crushes = Crush.roughly_spelled_like(params[:term]).paginate(:page => params[:page], :per_page => 10)
    end

  end


  def show
  end

  def new
    @crush = Crush.new
  end

  def create
    if !user_signed_in?
      redirect_to new_user_registration_path
    else
    @user = current_user
    @crush = Crush.new(:user => @user, :book_title=> params[:book_title], :genre => params[:genre], :author_name => params[:author_name], :author_country => params[:author_country], :description => params[:description], :quote => params[:quote])
      if @crush.save
        flash[:success] = "Ton coup de cœur est maintenant visible par tout.e.s ! :)"
        redirect_to crushes_path
      else
        flash[:errors] = @crush.errors.full_messages
        render new_crush_path
      end
    end
  end

  def edit
  end

  def update

    if @crush.update(crush_params)
    redirect_to @crush
    else
    render 'edit'
    end
  end

  def destroy
    @crush.destroy
    redirect_to crushes_path
  end

end

private

  def crush_params
    params.require(:crush).permit(:user, :book_title, :genre, :author_name, :author_country, :description, :quote)
  end

  def set_crush
    @crush = Crush.find(params[:id])
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :disable_nav, only: [:welcome_page]
  before_action :disable_footer, only: [:welcome_page]

    def index
    end


    def welcome_page
      @disable_nav = true
      @disable_footer = true
    end

  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])

  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def user_avatar(user)
      if user.avatar.attached?
        user.avatar
      else
        "default_image/default-avatar.jpeg"
      end
    end
  end

  

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/crush_libraries_helper.rb
module CrushLibrariesHelper
end

app/helpers/crushes_helper.rb
module CrushesHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/permission_helper.rb
module PermissionHelper

  def isAdmin?
    user_signed_in? && current_user.role == 'admin'
  end

  def isCrushAuthor?
    current_user == @crush.user
  end

  def isNotCrushAuthor?
    current_user != @crush.user
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_banner.html.erb
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://use.typekit.net/ecn4una.css">
    <link rel="stylesheet" href="https://use.typekit.net/ecn4una.css">
    <link rel="stylesheet" href="/css/style.css">


    <title>BANNER !</title>
</head>
<body>

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
  
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
    <div class="item active">
    <%= image_tag  "" , :style => "width:100%" %>


    </div>
    </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

app/views/layouts/_footer.html.erb
<footer>
  <div  class="container mt-5">
        <p class="float-right">
          <a href="#" class="footer-link"> ↑ Retour en haut</a>
        </p>

        <div class="text-footer">
            <div class="container footer-link">
                <div class="row py-2">
                    <div class="col-sm text-left">
                        <b>ReadHer</b>
                        <br><%= link_to "À propos",  pages_about_path, class:"footer-link" %>
                        <br><%= link_to "Manifesto",  pages_manifesto_path, class:"footer-link" %>

                    </div>

                    <div class="col-sm text-left">
                       <b>Support</b>
                       <br><%= link_to "Mentions légales", pages_mentions_legales_path, class:"footer-link" %>
                    </div>

                    <div class="col-sm text-left">
                      <b>Contact</b>
                       <br>Facebook
                       <br>Twitter
                    </div>
                </div>
                <hr>
                <div class="d-flex justify-content-center align-self  p-1" id="footer-credit">Readher © Paris — 2019</div>
            </div>

            <br>

        </div>
    </div>

    </footer>

app/views/layouts/_navbar.html.erb
<link rel="stylesheet" href="stylesheet/navbar.css">

<nav class="navbar navbar-expand-lg py-3 border-bottom border-white">
    <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <div class="container" onclick="myFunction(this)">
            <div class="bar1"></div>
            <!--burger-->
            <div class="bar2"></div>
            <!--burger-->
            <div class="bar3"></div>
            <!--burger-->
        </div>
    </button>

    <a class="navbar-brand" href="#">
        <%=link_to(image_tag("logo_readher.png", class: "logo_navbar pr-2"), crushes_path)%>
    </a>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav mr-auto text-center">
            <li class="nav-item mx-1">
                <%=link_to "Coups de cœur", crushes_path, class: "nav-link", anchor: "my_anchor"%>
            </li>

            <li class="nav-item pt-1 mx-1">
                <% if current_user %>
                    <%=link_to(image_tag("enveloppe-10-10.png", class: "box"), conversations_path)%>
                        <% end %>
            </li>

            <% if current_user== nil %>
                <li class="nav-item">
                    <%=link_to "Se connecter /", new_user_session_path, class: "nav-link", id: "login"%>
                </li>
                <li class="nav-item">
                    <%=link_to "Se connecter via facebook", user_facebook_omniauth_authorize_path, class: "nav-link", id: "login"%>
                </li>
                <li class="nav-item">
                    <%=link_to "Crée ton compte", new_user_registration_path, class: "nav-link" %>
                </li>
                <% else %>

                    <li class="nav-item">
                        <%=link_to "Profil", user_path(current_user.id), class: "nav-link" %>
                    </li>

                    <li class="nav-item">
                        <% if current_user %>
                            <%=link_to "Bibliothèque", library_path(current_user), class:"nav-link" %>
                    </li>
                    <% end %>

                        <li class="nav-item">
                            <a <%=link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "nav-link" %> </a>
                        </li>
                        <% end %>

        </ul>

        <form class="form-inline my-2 d-flex justifiy-content-center">

            <li class="nav-item" id="form-place" class="">

                <%=form_tag crushes_path, method: :get do %>
                    <%=text_field_tag "term", params[:term], placeholder: "Une auteure ou un livre", class: "form-control border-0 rounded-0" %>
                        <%=submit_tag 'Rechercher', class: "btn btn-outline-light mx-2 rounded-0", type: "submit"%>
                            <% end %>

            </li>
        </form>

    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>ReadHer</title>
    <%=csrf_meta_tags %>
        <%=csp_meta_tag %>

            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
            <link rel="stylesheet" href="https://use.typekit.net/ecn4una.css">
            <link rel="stylesheet" href="https://use.typekit.net/ecn4una.css">
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

            <link rel="stylesheet" href="stylesheet/style.css">
            <%=stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
                <%=javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
                    <%=favicon_link_tag asset_path( 'favicon.png') %>
                        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
                        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
                        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>

<body>
    <%= render 'layouts/navbar.html.erb' unless @disable_nav %>
        <div class= "container">
            <div class="alert alert_message text-center "><strong><%= flash[:success] %></strong>
            </div>
        </div>

        <% if notice %>
            <div class= "container col-md-12  d-flex justify-content-center pt-4 ">
                <p class="alert alert-success alert-dismissible fade show border-0 rounded-0" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <%= notice %>
                </p>
            </div>
            <% end %>
                <% if alert %>
                    <div class="container col-md-12  d-flex justify-content-center pt-4 ">
                        <p class="alert alert-danger alert-dismissible fade show border-0 rounded-0" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                            <%= alert %>
                        </p>
                    </div>
                    <% end %>

                        <%= yield %>
                            <br>
                            <br>
                            <br>
                            <%=render 'layouts/footer.html.erb' unless @disable_footer %>

</body>


</html>

app/views/pages/about.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.typekit.net/ecn4una.css">
    <link rel="stylesheet" href="https://use.typekit.net/ecn4una.css">

    <link rel="stylesheet" href="stylesheet/style.css">


    <title>ReadHer</title>
  </head>
  <body>

    <div class="text-center">


        <div class="container-fluid">
          <h1 class="display-3 text-center presentation_text m-4 p-4" id="punchline"> Les fondatrices </h1>
          <div class="row d-flex justify-content-center">

          <div class="col-sm-8  text-about ">
          <p>ReadHer est né d'une rencontre dans le cadre du bootcamp The Hacking Project. Trois apprenties codeuses, Nathalie Grego, Kenza Mezouar et Typhaine Charrat ont saisi l'opportunité offerte par la formation pour monter un réseau social répondant au manque de visibilité des écrivaines dans le monde de la littérature.<br><br>

            En tant que lectrice, Nathalie a toujours trouvé qu'il était plus difficile d'obtenir des références de lectures qui sortent des recommandations habituelles.
            En tant que marketer, elle souhaitait fonder une nouvelle communauté où il serait possible de partager ses affinités littéraires et culturelles. Le tout dans l'ouverture rendue possible par un modèle freemium. Avec ReadHer, son souhait est devenu réalité.<br><br>

            Designer graphique et typographe, Kenza s'est engagée dans le projet avec le désir de mettre sa sensibilité visuelle au service d'une nouvelle image de la littérature : moderne et ouverte à tout.e.s.<br><br>

            Littéraire de formation, c'est au cours de ses études et de son parcours personnel de lectrice que Typhaine s'est aperçue de l'absence des femmes dans le canon littéraire. Elle a imaginé ReadHer avec le désir de créer un nouvel espace qui serait entièrement dédié à la découverte de nouvelles voix et de nouvelles visions du monde.<br><br>

         </div>
        </div>
      </div>

    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/manifesto.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.typekit.net/ecn4una.css">
    <link rel="stylesheet" href="https://use.typekit.net/ecn4una.css">

    <link rel="stylesheet" href="stylesheet/style.css">


<title>ReadHer</title>
  <body>
    <div class="text-center">

     <div class="container-fluid">
      <h1 class="display-3 presentation_text m-4 p-4" id="punchline"> Manifesto</h1>
        <div class="row d-flex justify-content-center">

        <div class="col-sm-8 text-about ">
          <p> On a fait une expérience.<br><br>

          On a demandé à notre entourage et à nos rencontres de nous citer les écrivaines qu’ils connaissaient.<br><br>

          "Simone de Beauvoir, Marguerite Duras, Colette, Jane Austen, Virginia Woolf… " Et quelques dizaines d’autres sont souvent revenues, du genre Germaine de Staël, ou George Sand, pour les écrivaines du passé les plus célèbres. Amélie Nothomb, Marie Darrieussecq, Fatou Diome, Maylis de Kerangal, Annie Ernaux pour les écrivaines de l’actualité littéraire.<br><br>


          Parfois, moment de grâce, un nom nouveau venait enrichir la liste. Un nom français ignoré de l’actualité littéraire. Mais aussi un nom kenyan, taïwanais, brésilien.<br><br>

          Le sommet de l’iceberg.<br><br>

          Avez-vous déjà entendu parler de Clarice Lispector ? Et de Marina Tsvetaïeva ? Carson McCullers, Elsa Morante, Akiko Yosano, Wu Zao, Buchi Emecheta, Leylâ Erbil, Leslie Feinbberg, Dương Thu Hương, Jean Rhys, Flannery O’Connor, Geneviève Brisac, Karen Blixen, Jeannette Winterson, Catherine L. Moore, Alice Munro, Christine Jeanney, Violette Leduc, Chimamanda Ngozi Adichie, Katherine Mansfield, Rosemonde Lehmann, Djuna Barnes, Unica Zürn, Murasaki Shikibu, Yoko Ogawa, Cécile Portier, Juliette Mezenc ?<br><br>

          Un monde de littérature est à découvrir, et on voudrait que ReadHer vous aide à l’explorer.</p><br>

        </div>
      </div>
    </div>
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/welcome_page.erb
<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
</head>

<div class="text-center">
<%= image_tag "logo_readher.png", class: "mt-5 logo" %>
  <div class="container pt-5 mt-4">
    <h1 class="display-2  presentation_text my-2 animated fadeIn delay-1" id="catchline">
    TOUT.E.S LES HISTOIRES CHANGENT LE MONDE</h1>
  </div>
<h1 class="display-3 text-center presentation_text my-0 pt-2 animated fadeIn delay-1s" id="punchline"> Partage tes plus belles lectures.<br>Rencontre d'autres passionné.e.s.<br>Découvre de nouveaux chefs d'oeuvres.</h1>
  <div class="container d-flex justify-content-center mt-5 pt-4">
    <p> <%= link_to "ENTRER", crushes_path, class: "btn btn-dark mb-5 ", id: "btn-white"%> </p>
  </div>
</div>